"""
teams.py — team rosters.

Two sources, merged at import:

  TEAMS below   — the five pinned pro teams, hand-maintained here.
  rosters.json  — every league team, generated by build_rosters.py from the
                  DSE player portal and committed alongside the code.

A pinned team always wins a name collision, so editing TEAMS still overrides
whatever the portal says. Nothing else in the project needs to know which
source a team came from.

Player ids are Steam friend codes / SteamID3 account ids.
"""

import json
import os

TEAMS = {
    # ---------------------------------------------------------- NA
    "Poppers pupils": {
        "region": "NA",
        "players": {
            "Zeno": 1730032433,
            "LoMein": 1871021649,
            "Average": 399289886,
            "Lefaa": 114943410,
            "League": 1477660209,
            "Poppers": 1929248273,
        },
    },
    "Melee creeps": {
        "region": "NA",
        "players": {
            "JonJon": 244109796,
            "Goober": 1285605078,
            "Birdee": 1871217631,
            "Braeden": 225764206,
            "Saiah": 25821887,
            "DMB": 1049966963,
        },
    },
    # ---------------------------------------------------------- EU
    "Buff Enjoyers": {
        "region": "EU",
        "players": {
            "Zerggy": 35187362,
            "Lystic": 97533101,
            "Cosmetical": 483770846,
            "Obikym": 911856667,
            "Vraic": 344946432,
            "Hoot": 87241154,
        },
    },
    "Leviathan": {
        "region": "EU",
        "players": {
            "Irezumi": 136898005,
            "Overseas": 984254212,
            "Empty dreams": 5278896,
            "Dimov": 298305257,
            "Sai": 1045169707,
            "sanya_sniper": 906011648,
        },
    },
    "Abrahams": {
        "region": "EU",
        "players": {
            "Together": 298155885,
            "Saintmxsm": 1055638874,
            "Oses": 1840902834,
            "Sharyk": 81662458,
            "Freemok": 1009703898,
            "Arzo": 124540485,
        },
    },
}

REGIONS = ["NA", "EU"]

PINNED = set(TEAMS)                       # hand-maintained, never overwritten
ROSTERS_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "rosters.json")


def _load_rosters(path=ROSTERS_FILE):
    """Merge build_rosters.py output into TEAMS. Missing file is fine."""
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        return {}

    loaded = {}
    for name, info in (data.get("teams") or {}).items():
        players = {k: int(v) for k, v in (info.get("players") or {}).items()}
        if not players or name in PINNED:
            continue
        loaded[name] = {
            "region": info.get("region") or "",
            "division": info.get("division") or "",
            "team_id": info.get("team_id") or 0,
            "roles": info.get("roles") or {},
            "players": players,
        }
    TEAMS.update(loaded)
    return loaded


LEAGUE = _load_rosters()                  # {} when rosters.json is absent


def divisions():
    """Division names present in the loaded rosters, in league order."""
    seen = []
    for info in TEAMS.values():
        d = info.get("division")
        if d and d not in seen:
            seen.append(d)
    return sorted(seen)


def teams_in(division):
    return [n for n, t in TEAMS.items() if t.get("division") == division]


def search(query, limit=50):
    """Whitespace-insensitive substring match over team names."""
    q = "".join((query or "").lower().split())
    if not q:
        return sorted(TEAMS, key=str.lower)[:limit]
    hits = [n for n in TEAMS if q in "".join(n.lower().split())]
    return sorted(hits, key=str.lower)[:limit]


def info(name):
    """Everything known about one team."""
    t = TEAMS.get(name)
    if not t:
        return None
    return {"team": name, "region": t.get("region", ""),
            "division": t.get("division", ""), "team_id": t.get("team_id", 0),
            "pinned": name in PINNED, "players": dict(t["players"]),
            "roles": dict(t.get("roles") or {})}


def team_names(region=None):
    """Team names, optionally just one region's."""
    return [name for name, t in TEAMS.items()
            if region is None or t["region"] == region]


def roster(selection):
    """
    selection: a team name, a region ("NA" / "EU"), or "All".
    -> (list of account_ids, {account_id: {"ign":..., "team":..., "region":...}})
    """
    if selection == "All":
        names = team_names()
    elif selection == "All (pinned)":
        names = sorted(PINNED, key=str.lower)
    elif selection in REGIONS:
        names = team_names(selection)
    elif selection in TEAMS:
        names = [selection]
    elif teams_in(selection):
        names = sorted(teams_in(selection), key=str.lower)
    else:
        raise ValueError(f"unknown selection: {selection!r}")

    ids, labels = [], {}
    for team in names:
        entry = TEAMS[team]
        for ign, account_id in entry["players"].items():
            ids.append(account_id)
            labels[account_id] = {"ign": ign, "team": team,
                                  "region": entry.get("region", ""),
                                  "division": entry.get("division", "")}
    return ids, labels


def roster_many(selections):
    """
    Combine several selections into one roster.
    selections: any mix of team names, regions, and "All".
    -> (ids, {account_id: {"ign","team","region"}})
    """
    ids, labels = [], {}
    for name in selections:
        got_ids, got_labels = roster(name)
        for account_id in got_ids:
            if account_id not in labels:
                ids.append(account_id)
            labels[account_id] = got_labels[account_id]
    return ids, labels


def choices(include_league=False):
    """
    Everything you can pick, in menu order. The league teams are left out
    unless asked for -- 180 entries do not belong in a menu; use search().
    """
    pinned = sorted(PINNED, key=str.lower)
    if not include_league:
        return ["All (pinned)", *REGIONS, *pinned]
    return ["All", "All (pinned)", *REGIONS, *divisions(),
            *sorted(TEAMS, key=str.lower)]


def find_player(account_id):
    """
    Is this account on any roster? -> {"ign", "team", "region"} or None.
    Used to recognise a sub who is themselves a pro on another team.
    """
    for team in list(PINNED) + [t for t in TEAMS if t not in PINNED]:
        entry = TEAMS[team]
        for ign, aid in entry["players"].items():
            if aid == account_id:
                return {"ign": ign, "team": team,
                        "region": entry.get("region", ""),
                        "division": entry.get("division", "")}
    return None
